bucket_name: 'apidoorlocksystem-dev'
profile_name: 'group-infinys'
table_users: 'Users-3rb3eizz55aklelrckuz5zg3dy-dev'

photo_skip: 1
threshold: 0.5

model_dir: './facenet_weights.h5'

door_pin: 1
topic: 'iot/doors'

endpoint: ''
root_ca_path: './things/certs/AmazonRootCA1.pem'
cert_path: './things/certs/iot-door-cert.pem.crt'
private_key_path: './things/certs/iot-door-private.pem.key'
port: 8883
client_id: 'Webcam'